// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDNlj4MVLoNra91e8Q4yKeDVxtbDsijNuM',
//     appId: '1:967281617059:web:8c27383bc06338ef9bf716',
//     messagingSenderId: '967281617059',
//     projectId: 'c2ctaker',
//     authDomain: 'c2ctaker.firebaseapp.com',
//     storageBucket: 'c2ctaker.appspot.com',
//     measurementId: 'G-C4MQ47BLH3',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDifi1H1uuZdr5Pv2g6PTypUf51UlqLhFo',
//     appId: '1:967281617059:ios:3f13cb46075dd2029bf716',
//     messagingSenderId: '967281617059',
//     projectId: 'c2ctaker',
//     storageBucket: 'c2ctaker.appspot.com',
//     iosBundleId: 'com.example.care2caretaker',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDNlj4MVLoNra91e8Q4yKeDVxtbDsijNuM',
//     appId: '1:967281617059:web:71f28a1697906eee9bf716',
//     messagingSenderId: '967281617059',
//     projectId: 'c2ctaker',
//     authDomain: 'c2ctaker.firebaseapp.com',
//     storageBucket: 'c2ctaker.appspot.com',
//     measurementId: 'G-NQ8XERN3RF',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDifi1H1uuZdr5Pv2g6PTypUf51UlqLhFo',
//     appId: '1:967281617059:ios:3f13cb46075dd2029bf716',
//     messagingSenderId: '967281617059',
//     projectId: 'c2ctaker',
//     storageBucket: 'c2ctaker.appspot.com',
//     iosBundleId: 'com.example.care2caretaker',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBPfnjGnbzOLUlYqWSPuOBz7vVSYAFblks',
//     appId: '1:967281617059:android:c72a2660bfbf89949bf716',
//     messagingSenderId: '967281617059',
//     projectId: 'c2ctaker',
//     storageBucket: 'c2ctaker.appspot.com',
//   );
//
// }


//////////////////
/*import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get care2care {
    return const FirebaseOptions(
      apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
      appId: '1:496441455277:android:23d1d1089abd3bbc774c24',
      messagingSenderId: '496441455277',
      projectId: 'c2cpatient-d4526',
      storageBucket: 'c2cpatient-d4526.appspot.com',
    );
  }

  static FirebaseOptions get care2caretaker {
    return const FirebaseOptions(
      apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
      appId: '1:496441455277:android:662af5d3bc954389774c24',
      messagingSenderId: '496441455277',
      projectId: 'c2cpatient-d4526',
      storageBucket: 'c2cpatient-d4526.appspot.com',
    );
  }

  static FirebaseOptions get currentPlatform {
    // Modify this logic based on the package name or other criteria to select the correct options
    const String packageName = "com.example.care2caretaker"; // Change based on the running app
    if (packageName == "com.example.care2care") {
      return care2care;
    } else {
      return care2caretaker;
    }
  }
}*/
import 'dart:io';
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {

  static FirebaseOptions get care2care {

    bool isAndroid = Platform.isAndroid;
    if(isAndroid) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyBFzoMa0Qn3hH_WFT2qhcmnJ_cWN5GmjVM',
        appId: '1:496441455277:android:23d1d1089abd3bbc774c24',
        messagingSenderId: '496441455277',
        projectId: 'c2cpatient-d4526',
        storageBucket: 'c2cpatient-d4526.appspot.com',
      );
    } else {
      return FirebaseOptions(
        apiKey: 'AIzaSyARzj9bC7XvdxuxKDW2-mdnhpRpzoXwxnQ',
        appId: '1:496441455277:ios:1a44c410aa9835ea774c24',
        messagingSenderId: '496441455277',
        projectId: 'c2cpatient-d4526',
        storageBucket: 'c2cpatient-d4526.appspot.com',
      );
    }
  }

  static FirebaseOptions get currentPlatform {
    return care2care;
  }

}