// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlj4MVLoNra91e8Q4yKeDVxtbDsijNuM',
    appId: '1:967281617059:web:8c27383bc06338ef9bf716',
    messagingSenderId: '967281617059',
    projectId: 'c2ctaker',
    authDomain: 'c2ctaker.firebaseapp.com',
    storageBucket: 'c2ctaker.appspot.com',
    measurementId: 'G-C4MQ47BLH3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifi1H1uuZdr5Pv2g6PTypUf51UlqLhFo',
    appId: '1:967281617059:ios:3f13cb46075dd2029bf716',
    messagingSenderId: '967281617059',
    projectId: 'c2ctaker',
    storageBucket: 'c2ctaker.appspot.com',
    iosBundleId: 'com.example.care2caretaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlj4MVLoNra91e8Q4yKeDVxtbDsijNuM',
    appId: '1:967281617059:web:71f28a1697906eee9bf716',
    messagingSenderId: '967281617059',
    projectId: 'c2ctaker',
    authDomain: 'c2ctaker.firebaseapp.com',
    storageBucket: 'c2ctaker.appspot.com',
    measurementId: 'G-NQ8XERN3RF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifi1H1uuZdr5Pv2g6PTypUf51UlqLhFo',
    appId: '1:967281617059:ios:3f13cb46075dd2029bf716',
    messagingSenderId: '967281617059',
    projectId: 'c2ctaker',
    storageBucket: 'c2ctaker.appspot.com',
    iosBundleId: 'com.example.care2caretaker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfnjGnbzOLUlYqWSPuOBz7vVSYAFblks',
    appId: '1:967281617059:android:c72a2660bfbf89949bf716',
    messagingSenderId: '967281617059',
    projectId: 'c2ctaker',
    storageBucket: 'c2ctaker.appspot.com',
  );

}